import {
  Product,
  ProductAvailability,
  ProductStatusTone,
  ProductUnitMode,
} from './models/product.model'

export const PRODUCTS_SEED: Product[] = [
  {
    id: 'potato',
    name: 'Картофель',
    subtitle: 'Местный, КХ',
    imageUrl: '/products/potato.jpg',
    statusEmoji: '🟢',
    statusText: 'Свежий привоз сегодня в 08:00',
    statusTone: ProductStatusTone.Fresh,
    availability: ProductAvailability.Warehouse,
    basePrice: 150,
    minOrder: 'Минимальный опт от 1 тонны',
    location: 'Склад №1, Уральск',
    warehouseId: 'warehouse-1',
    bookingNote: null,
    unitMode: ProductUnitMode.Tons,
    sliderMin: 1,
    sliderMax: 20,
    sliderStep: 0.5,
    defaultVolume: 5,
  },
  {
    id: 'onion',
    name: 'Лук репчатый',
    subtitle: 'Оптовая партия',
    imageUrl: '/products/onion.jpg',
    statusEmoji: '🟡',
    statusText: 'В наличии, на складе 3 дня',
    statusTone: ProductStatusTone.Stock,
    availability: ProductAvailability.Warehouse,
    basePrice: 110,
    minOrder: 'Минимальный опт от 1 тонны',
    location: 'Склад №1, Уральск',
    warehouseId: 'warehouse-1',
    bookingNote: null,
    unitMode: ProductUnitMode.Tons,
    sliderMin: 1,
    sliderMax: 20,
    sliderStep: 0.5,
    defaultVolume: 3,
  },
  {
    id: 'carrot',
    name: 'Морковь',
    subtitle: 'Мытая',
    imageUrl: '/products/carrot.jpg',
    statusEmoji: '🚚',
    statusText: 'В пути, ожидается завтра',
    statusTone: ProductStatusTone.Transit,
    availability: ProductAvailability.Transit,
    basePrice: 130,
    minOrder: 'Минимальный опт от 1 тонны',
    location: 'Таможенный пост «Маштаково» / Самарская трасса',
    warehouseId: null,
    bookingNote: 'Доступно бронирование',
    unitMode: ProductUnitMode.Tons,
    sliderMin: 1,
    sliderMax: 20,
    sliderStep: 0.5,
    defaultVolume: 4,
  },
  {
    id: 'tomato',
    name: 'Томаты',
    subtitle: 'Тепличные',
    imageUrl: '/products/tomato.jpg',
    statusEmoji: '🟢',
    statusText: 'Свежий привоз сегодня',
    statusTone: ProductStatusTone.Fresh,
    availability: ProductAvailability.Warehouse,
    basePrice: 650,
    minOrder: 'Опт от 500 кг',
    location: 'Склад №2, охлаждаемый',
    warehouseId: 'warehouse-2',
    bookingNote: null,
    unitMode: ProductUnitMode.Kg,
    sliderMin: 500,
    sliderMax: 5000,
    sliderStep: 100,
    defaultVolume: 1500,
  },
  {
    id: 'cabbage',
    name: 'Капуста',
    subtitle: 'Белокочанная',
    imageUrl: '/products/cabbage.jpg',
    statusEmoji: '🟢',
    statusText: 'Свежий привоз сегодня в 10:30',
    statusTone: ProductStatusTone.Fresh,
    availability: ProductAvailability.Warehouse,
    basePrice: 95,
    minOrder: 'Минимальный опт от 1 тонны',
    location: 'Склад №1, Уральск',
    warehouseId: 'warehouse-1',
    bookingNote: null,
    unitMode: ProductUnitMode.Tons,
    sliderMin: 1,
    sliderMax: 20,
    sliderStep: 0.5,
    defaultVolume: 2,
  },
]
